- hosts: all
  become: true
  tasks:
     - name: latest Apache version installed
       yum:
      name: httpd
      state: latest
- name: Apache enabled and running
  service:
   name: httpd
   enabled: true
   state: started
- name: copy index.html
  copy:
  src: /home/ec2-user/index.html
  dest: /var/www/html/index.html

# This Will Install Apache Server
